# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3'

#Define services
services:


  #Back-end Spring Boot Application
  vdf-car-spring-app:
    #The docker file in  build the jar and provides the docker image with the following name.
    build: .
    container_name: vdf-car-spring-app

    ports:
      - 8090:8090 # Forward the exposed port 8090 on the container to port 8090 on the host machine



